### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Redvanisation**

### CODE REVIEW

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Game is hard to play!!!

I think the game is really hard to play because of what you required as the player's input. I expect to be able to input ints in the range `1..9` but apparently, it was not working. It was requiring me to input some x, y coordinates which I couldn't figure out and most people won't figure out as well. Please simply make the player's input to be int in the range `1..9`.

Secondly, I think to have several methods to test the winning combination is counter-intuitive. You should have a single method winning combinations which can validate all possible winnings and not have like `verticals` `horizontal` `diagonal` as you have in your code.

Please, I expect to see more commits from the student with fewer commits. It has not been evenly distributed so far.

Work on these and request another review.

Happy coding!

**Review by JamesOkunlade — CHANGES_REQUESTED** [review]
### Good Improvement, not enough though.

image

It's good I can play with numbers in the range `1..9` now. However, It would make more sense if the grid spaces can be represented with the numbers `1..9` instead of the `-` that's currently there.

Also, refactor the line that says `"...please enter the coordinates in the form: x, y"` to represent the current state of the game. i.e. `"...please enter slot number in range 1 to 9"`. 

Please fix these and request for another review. Reach out to me on slack if you have any question.

Happy coding!

**Review by JamesOkunlade — APPROVED** [review]
### Cool!!

Nice improvements and thanks for your patience.

This is good to go now. Please merge to master, close pull request and fill the completion form.

Good luck with your future projects. :+1::+1:

**Comment by Redvanisation** [comment]
Thank you for the review!

**Pull request merged**
